# Generated by Django 5.0.3 on 2024-04-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.profile'),
        ),
    ]
